### ISSUE TITLE
make distcheck fails due to missing optional dependencies

### ISSUE THREAD

**Issue by tmatth** [libmapper/libmapper#1]
If I try to run "make distcheck" for libmapper without javac installed (for example), it will fail with the following error:

config.status: error: cannot find input file: `jni/Makefile.in'

The same issue is true for swig:
config.status: error: cannot find input file: `swig/Makefile.in'

My guess is that in the toplevel Makefile.am, you have the subdirs swig and jni as conditionally defined (i.e. @SWIG@), however in configure.ac they are always expected by the AC_CONFIG_FILES macro (i.e. swig/Makefile).

**Comment by radarsat1** [comment]
Ha, I haven't even gotten as far as trying distcheck.  ;)  Thanks for the report, I'll give it some attention.  Actually I thought it was impossible to make things conditional in the AC_CONFIG_FILES macro.  I'll take a look.

**Comment by radarsat1** [comment]
distcheck-clean as of 6b89352c.
