### ISSUE TITLE
Python libmapper extension improperly installed

### ISSUE THREAD

**Issue by sofian** [libmapper/libmapper#10]
This actually happened while trying to run webmapper from a fresh install. Libmapper was also installed from a fresh pull of master branch.

It looks like under the compilation process of libmapper, Swig doesn't generate any constructor for the mapper class.

I'm using Ubuntu 12.04 and Python2.7.

```
$ ./webmapper.py
Traceback (most recent call last):
  File "./webmapper.py", line 49, in <module>
    monitor = mapper.monitor()
  File "/usr/local/lib/python2.7/dist-packages/mapper.py", line 211, in __init__
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
AttributeError: No constructor defined
```

**Comment by radarsat1** [comment]
This is related to the update to swig 2.x.  Definitely a problem.

**Comment by sofian** [comment]
Any quick fix?

**Comment by radarsat1** [comment]
Working on it.

**Comment by radarsat1** [comment]
I pushed a reversion of the change to support SWIG 2.x.  Unfortunately I think the patch was not enough.  Mahtab was also having problems with it.  So, pull master, and install SWIG 1.3.40 to make it work.

Note, after doing this, I'm actually getting a segfault I don't understand in test.py, but for attributes, a feature that shouldn't affect you.

**Comment by sofian** [comment]
Ok this fixes the issue on my side too. I can now run webmapper. Thanks!
