### ISSUE TITLE
Should check for proper version of liblo

### ISSUE THREAD

**Issue by aalex** [libmapper/libmapper#11]
Otherwise, it might fail since it cannot link to lo_bundle_count.
(it does on Ubuntu Precise)

**Comment by radarsat1** [comment]
We've been using feature checks instead of version checks, but if it's failing then this is certainly a bug.  I'll check it out when I get a chance.

That said, libmapper should currently be compiled against the git master version of liblo.

**Comment by radarsat1** [comment]
This seems fixed waaaay back in af80a53afaf221cc5027f4496aaaa5fc9ad1ed2b
