### ISSUE TITLE
Signal deletion callback

### ISSUE THREAD

**Issue by mysteryDate** [libmapper/libmapper#14]
Though my monitor is automatically requesting "all," I do not receive a MDB_REMOVE message if a signal is deleted within a device. If the entire device is deleted, all child signals are successfully deleted, it is only a problem if the device persists (which is problematic with the new Max bindings).
  The MDB_MODIFY also has a callback problem for signals, though MDB_NEW appears to work.

**Comment by malloch** [comment]
This issue has been solved in version 0.4
