### ISSUE TITLE
enable issue-tracker on libmapper/libmapper

### ISSUE THREAD

**Issue by umlaeute** [libmapper/libmapper#17]
it seems that this project has been moved to https://github.com/libmapper/libmapper

unfortunately, github does not enable *issue trackers* for forked projects by default.
so it would be good to enable the issue tracker *there*.

(obviously this is the wrong repo to report the problem; however, i hope that the people involved can deal with the problem nevertheless)

**Comment by radarsat1** [comment]
Thank you, done.

**Comment by umlaeute** [comment]
thanks; afaik there is no way to move issues between repositories on github (ha, gitlab can do this :-).

should i recreate the other issues over there?
