### ISSUE TITLE
package_version broken on non-git-clones

### ISSUE THREAD

**Issue by umlaeute** [libmapper/libmapper#18]
in [`configure.ac`](https://github.com/radarsat1/libmapper/blob/master/configure.ac#L3), the package's version is calculated with

    git describe --always

While I understand the urge of only having to create a release via a single command (`git tag`), this breaks if you download the `release tarball` (because then there is no git repository, and `git describe` will return an empty string).
A non-existant `PACKAGE_VERSION` gives also some spurious errors (e.g. #19)

**Comment by radarsat1** [comment]
Ideally there should be two cases:
1) You are working on libmapper, therefore should be using git
2) You downloaded the tarball, therefore should be configuring using the provided configure script, which has the version number baked in.

So what situation do you have where this causes a problem?

I just downloaded and compiled libmapper-0.4.tar.gz from libmapper.org and it seems to work from the included configure script.  Although it seems a git checksum made its way into the version number, but this doesn't seem to break things.

**Comment by umlaeute** [comment]
my use case is: packaging libmapper for Debian

the workflow is:
- import libmapper-0.4.tar.gz from libmapper.org
- run `autoreconf`: this is an *automatic* and routine operation on all Debian builds, as there have been plenty of issues with outdated `config.guess` scripts and probably others; (remember that Debian builds any package on a multitude of architectures, some of which most upstreams have never heard nor cared about; it is those architectures that often require a `configure` script built from up-to-date sources)
- build the package

so the problem seems to be, that i am both using the release tarball (without the git tree) *and* run autoreconf (thus invalidating anything that has been pre-baked into `configure`).

if my request severely disrupts your workflow, then i will of course accept that (and continue to patch the `configure.ac` to contain a proper version string). but of course i'd be thankful if there was no need to patch.

(ping @malloch)

**Comment by radarsat1** [comment]
Yep, no worries, procedures have changed since 7 or 8 years ago is the only problem here ;)  People downloading for use straight from github etc.. and depending on autoreconf, things didn't used to be like that but we should get up to date.  So my answer is that it's worth fixing this.  However, after this and your other issue are closed I'll close issues here and we can move over to libmapper/libmapper.
