### ISSUE TITLE
Mac OS X Installation problem

### ISSUE THREAD

**Issue by sofian** [libmapper/libmapper#2]
I ran into some problems while installing the project on Mac OS X. The installation process is not clear.

The tutorial.txt text explains to run ./configure but you need to run autogen.sh to actually generate it and this is not specified in the tutorial.txt. It should anyway be explained in an INSTALL file.

I intuitively ran the autogen.sh script which did the thing but then ran into problem cause I needed to install liblo:
http://liblo.sourceforge.net/

I installed liblo very easily using the INSTALL instructions:
./configure
make
make install

It wasn't super clear what to do next. I still got an error when running ./configure:

<pre>
No package 'liblo' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables liblo_CFLAGS
and liblo_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
</pre>

It was not very clear but I figured out I had to do this:
export liblo_CFLAGS=-L/usr/local/lib
export liblo_LIBS=-llo

Liblo is found but now I'm stuck with the following problem:

<pre>
[tats@TatsLab.local libmapper] # make
Making all in src
make  all-am
Making all in include
make[1]: Nothing to be done for `all'.
Making all in test
make[1]: Nothing to be done for `all'.
Making all in examples
Making all in pwm_synth
make[2]: Nothing to be done for `all'.
Making all in py_tk_gui
swig -I../../examples/pwm_synth -I../../include -c++ \
        -python -o /pwm_wrap.cxx ./pwm.i
pwd
/Users/tats/schrift/doc/education/doctorat/emerge/devel/libmapper/examples/py_tk_gui
cd  && env CFLAGS="" python setup.py build_ext
/System/Library/Frameworks/Python.framework/Versions/2.5/Resources/Python.app/Contents/MacOS/Python: can't open file 'setup.py': [Errno 2] No such file or directory
make[2]: *** [_pwm.so] Error 2
rm /pwm_wrap.cxx
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
[tats@TatsLab.local libmapper] # find . -iname pwm_wrap.cxx
[tats@TatsLab.local libmapper] # 
</pre>

**Comment by radarsat1** [comment]
Hi Sofian,

Glad you figured out the prerequesites.  The reason the tutorial
doesn't mention autogen.sh is that the "configure" script comes
pre-prepared in the tarball download.  However, you're right we could
mention it there.

For the error you're getting, first maybe try configuring without
Python or Java, see if that works:

```
$ ./configure --disable-swig --disable-java
```

You mentioned previously that you're running 10.5, I've only tested on
10.6; so I don't know but that could be a source of discrepancies in
terms of paths to header files and such.

Steve

On Mon, May 16, 2011 at 10:49 PM, sofian
reply@reply.github.com
wrote:

**Comment by radarsat1** [comment]
More extensive build instructions have been added to the documentation.  Please re-open if build problems persist.

**Comment by sofian** [comment]
I had the exact same problem under Linux btw. The new version does fix this issue.
