### ISSUE TITLE
java broken, Property class is missing

### ISSUE THREAD

**Issue by radarsat1** [libmapper/libmapper#21]
I got Java working again in terms of finding the JDK properly (at least on Ubuntu) and linking against jni.h.  I had to fix a small problem with paths after the convergent5 merge, where some files were in jni/mapper and some were in jni/Mapper.  In any case, works now, but I still can't compile JNI bindings.  There are references to `class Property` but I can't find `Property.class` anywhere, even in the project history.  Ideas?

**Comment by malloch** [comment]
Oops! Added now.

**Comment by radarsat1** [comment]
Sweet.. seems fixed but I've got another Java-related error now still in reference to the Property class.  I'll re-open or create a new issue if I can't figure it out.

**Comment by radarsat1** [comment]
Sorry false alarm, I must have pulled just before you pushed efc62c1cb.  Seems to work now, I ran test.java successfully on my machine!
