### ISSUE TITLE
integer size warnings in mapperjni.c

### ISSUE THREAD

**Issue by malloch** [libmapper/libmapper#25]
Commit fe793811 changed two printf format strings from "%llu" to "%lu" to resolve integer size warnings (presumably on Linux) but the mapper_id type is uint64_t. Now I get integer size warnings compiling on OSX!

**Comment by radarsat1** [comment]
D'oh ;)

Maybe some autoconfness is needed then...
I did compile on OS X before tagging, but I guess I didn't notice the warnings, sorry about that.

**Comment by radarsat1** [comment]
Seems it was probably better to leave it as %llu!
http://jhshi.me/2014/07/11/print-uint64-t-properly-in-c/

I don't recall if we're already assuming C99... I guess if we are using uint64_t as a type then we are, so we can use PRIu64.

**Comment by malloch** [comment]
Do you think we should be supporting C90?

**Comment by radarsat1** [comment]
Best thing is to always do feature checking.  The patch checks whether inttypes.h is available.
