### ISSUE TITLE
additional value received in signal update using CPP bindings

### ISSUE THREAD

**Issue by johnty** [libmapper/libmapper#26]
I just noticed a curious bug with the CPP bindings.

To reproduce:
-  replace test/testcpp.cpp with [this stripped down version](https://gist.github.com/johnty/db3ec4ecd4a30f656029ffb3365a4fb8) and compile. It just creates one dev with a single signal hooked up to the example signal handler that spits out the received value(s)
- run test/test alongside testcpp
- in webmapper, map one of the single valued outputs from test to the input signal of testcpp.

Following shows the output:

```
--> destination got testinput FLOAT- 0.000000 DOUBLE- 0.000000
--> destination got testinput FLOAT- 1.000000 DOUBLE- 0.000000
--> destination got testinput FLOAT- 2.000000 DOUBLE- 0.000000
--> destination got testinput FLOAT- 3.000000 DOUBLE- 0.000000
--> destination got testinput FLOAT- 4.000000 DOUBLE- 0.000000
--> destination got testinput FLOAT- 5.000000 DOUBLE- 0.000000
--> destination got testinput FLOAT- 6.000000 DOUBLE- 0.000000
```

*edit* ignore this I am an idiot: missing break in the test code :P

**Comment by radarsat1** [comment]
> missing break in the test code

classic ;)
