### ISSUE TITLE
Signal vector length capped at 128

### ISSUE THREAD

**Issue by maxgraf96** [libmapper/libmapper#31]
Hi!

First of all, thank you! I'm really enjoying your library, it's pretty amazing to work with. I'm experiencing strange behaviour however, and want to open an issue here because I couldn't find any hint to a solution in the docs, tutorials or on the web.
My issue lies in an apparent limit to the length that output signal vectors can take. I noticed it when trying to add an output signal that periodically sends a vector of 257 floats to a libmapper device. If the length is set to 257 the generated Signal object is ```NULL``` however. However it does work with length values _up to 128_. From 129 on my ```_sig``` object is ```NULL```. The same behaviour is observed for integer and double signal types.

More specifically - if I initialise my signal as follows
```std::unique_ptr<mapper::Signal> sensor2 = std::make_unique<mapper::Signal>(dev->add_output_signal("sensor2", 128, 'f', 0, 0, 0));```
everything is fine. The ```_sig``` object contained in ```sensor2``` is ```NULL``` when the initialisation looks like ```std::unique_ptr<mapper::Signal> sensor2 = std::make_unique<mapper::Signal>(dev->add_output_signal("sensor2", 129, 'f', 0, 0, 0));```, however.

I'm running the latest C++ version of libmapper built from source on macOS Catalina.
I'd be grateful for any hints, as a signal length of 128 would impose quite a big restriction on the functionality for me.

Thank you!

**Comment by radarsat1** [comment]
I *think* that limit is arbitrary.  It's not really envisioned to use massive signal lengths with libmapper.  But you can certainly feel free to change it and report if it works well.. check `MAPPER_MAX_VECTOR_LEN` in `mapper_internal.h`.

**Comment by maxgraf96** [comment]
Thank you, that makes sense! I think I can do with the limit, but I'll update this issue if it works! Consider it closed :)
