### ISSUE TITLE
MapLooper compatibility broken

### ISSUE THREAD

**Issue by badebold** [libmapper/libmapper#36]
Hi @malloch,

It seems that commit 6fe52fd8b447701cd66d4b1abb42e915337e26a8 breaks compatibility with MapLooper. It still compiles fine, but during runtime the output of the looping map is silent.

Do you have an idea about what could have caused the issue?

**Comment by malloch** [comment]
Hi @mathiasbredholt, I created a pull request for MapLooper that should fix the problem. I think the current behaviour of libmapper is correct but I need to think about it some more!

**Comment by badebold** [comment]
Hi @malloch, thanks a lot for the pull request! This fixes my issue!
