### ISSUE TITLE
Segfault when initializing mapper::Device after default constructor has been called?

### ISSUE THREAD

**Issue by DocSunset** [libmapper/libmapper#38]
Hi team.

Can anyone else replicate this issue? I have two minimum programs:

```cpp
// faulty.cpp
#include <mapper/mapper_cpp.h>

struct Foo
{
    mapper::Device dev;
    mapper::Signal sig;

    void init()
    {
        dev = mapper::Device("/foo");
        dev.poll(); // seg fault
        //while (dev.poll()) if (dev.ready()) break;
        //sig = dev.add_signal(mapper::Direction::INCOMING, "/bar", 1, mapper::Type::FLOAT);
    }
};

int main()
{
    Foo foo;
    foo.init();
}

// $ g++ -I/usr/local/include -L/usr/local/lib -lmapper faulty.cpp -o faulty
// $ ./faulty
// Segmentation fault (core dumped)
```

```cpp
// acceptable.cpp
#include <mapper/mapper_cpp.h>

struct Foo
{
    mapper::Device dev = mapper::Device("/foo");
    mapper::Signal sig;

    void init()
    {
        while (dev.poll()) if (dev.ready()) break;
        sig = dev.add_signal(mapper::Direction::INCOMING, "/bar", 1, mapper::Type::FLOAT);
    }
};

int main()
{
    Foo foo;
    foo.init();
}

// $ g++ -I/usr/local/include -L/usr/local/lib -lmapper acceptable.cpp -o acceptable
// $ ./acceptable
// $ echo $?
// 0
```

Unless I'm mistaken, the only difference between these programs is that in `faulty.cpp` the device is default constructed (so `_obj = nullptr` etc.), and later initialized in the `init` function by the line `dev = mapper:Device("/foo");`. But it appears as though it is not actually being initialized? I would have thought the constructor `Device(const Device& orig)` would end up being called...

**Comment by DocSunset** [comment]
Looking in the debugger, it appears that `mapper::Device("/foo");` does correctly initialize an anonymous mapper::Device. It appears the device is copied to `dev`. However, the expected constructor `Device(const Device& orig)` never gets called. The anonymous device's destructor is then immediately called, which frees the underlying `mpr_dev`. So the problem, I guess, is that one of the constructor's automatically generated by C++ is being called instead of the defined one.

**Comment by DocSunset** [comment]
Ignore the above reference, I meant to say #40

**Comment by malloch** [comment]
Hi Travis,

I think the correct way to initialize the device would be something like:

```cpp
#include <mapper/mapper_cpp.h>

struct Foo
{
private:
    mapper::Device dev;
    mapper::Signal sig;

public:
    Foo() : dev("foo") {}

    void init()
    {
        while (dev.poll()) if (dev.ready()) break;
        sig = dev.add_signal(mapper::Direction::INCOMING, "bar", 1, mapper::Type::FLOAT);
    }
};

int main()
{
    Foo foo;
    foo.init();
}
```

**Comment by DocSunset** [comment]
Yeah, I guess that would be equivalent to the latter snippet I posted earlier. In both cases `dev` gets initialized with a name during the constructor of `Foo` and the default constructor of `mapper::Device` is never called.

Arguably, since the segfaulty method of initializing compiles and looks reasonable, it should also work.

**Comment by malloch** [comment]
@DocSunset should be fixed now – can you verify? Thanks!

**Comment by DocSunset** [comment]
It works! Thanks @malloch!
