### ISSUE TITLE
Feature request: get list of local devices

### ISSUE THREAD

**Issue by DocSunset** [libmapper/libmapper#39]
I would like to have a list of local devices, and it seems like if I create my own mpr_graph and pass it to all the devices I make that it should be possible to get such a list from a mpr_graph, something like this:

```c
mpr_graph graph = mpr_graph_new(MPR_OBJ);
mpr_dev_new("/dev1", graph);
mpr_dev_new("/dev2", graph);
// ...
mpr_dev_new("/devN", graph);

int truebool = 1;
mpr_list local_devices = mpr_list_filter(mpr_graph_get_list(MPR_DEV), 0, 1, MPR_BOOL, &truebool, MPR_OP_EQ);
// iterate over your local devices
```

I'm not confident I understand how mpr_list_filter is supposed to work, but it's moot anyways since there is no function `mpr_graph_get_list`. Any particular reason why not?

I guess a shared `mpr_graph` could have an even more efficient way of getting a list of local devices, since its internal `mpr_net` already has a member `struct _mpr_local_dev **devs;` that is presumably exactly the list I'm looking for, just waiting to be passed back to me:

```c
int mpr_graph_get_local_devs(mpr_graph graph, mpr_dev * devs_out)
{
    devs_out = (mpr_dev *) graph->net.devs;
    return graph->net.num_devs;
}
```

Or something similar.

Aside: It seems like there is a lot of room for optimizing the way that devices created within the same process interact. Right now, if I understand correctly, they all have their own graph, they do their own networking, and they communicate via the network only. If you give them all the same `mpr_graph` when you create them, then they share the graph, but it seems they are unaware of this; for instance, every device will separately call `mpr_net_send`. For a program where there are lots of devices created locally, it could be nice to have specific APIs to more efficiently process all of their needs, handling things without recourse to the network where possible. As it stands though, having a convenient way to get a list of local devices so that you can poll them all at the same time without having to keep your own redundant list would be a good place to start.

**Comment by malloch** [comment]
The function you are looking for is `mpr_graph_get_objs()` so the filter would look like this:

~~~ c
int true = 1;
mpr_list devlist = mpr_graph_get_objs(graph, MPR_DEV);
devlist = mpr_list_filter(devlist, MPR_PROP_IS_LOCAL, NULL, 1, MPR_BOOL, &true, MPR_OP_EQ);
~~~

a bit verbose perhaps but it's quite flexible. It looks tidier in e.g. C++:

~~~ cpp
List<Device> devlist = graph.devices().filter(Property::IS_LOCAL, true);
~~~

**Comment by malloch** [comment]
Fixed and tested.

**Comment by malloch** [comment]
Leaving a note for anyone referring to this conversation: The function has been renamed to `mpr_graph_get_list()` so the example above now looks like this:
~~~ C
int true = 1;
mpr_list devlist = mpr_graph_get_list(graph, MPR_DEV);
devlist = mpr_list_filter(devlist, MPR_PROP_IS_LOCAL, NULL, 1, MPR_BOOL, &true, MPR_OP_EQ);
~~~
