### ISSUE TITLE
Mapper Signal Min and Max Not Set Properly

### ISSUE THREAD

**Issue by mghamsar** [libmapper/libmapper#5]
I'm using libmapper to read in data coming in from the serial port using pymapper. When creating the mapper signals I set my min and max values to 0 and either 128 or 255 depending on the signal. When reading the outgoing mapper signals however, the mins seem to also be set to 128/255 as opposed to 0.

**Comment by radarsat1** [comment]
I'm afraid I haven't been able to reproduce the issue.  I'll have to check on your computer.

**Comment by malloch** [comment]
As far as I know no-one has been able to reproduce this issue... close?

**Comment by radarsat1** [comment]
For now, I guess we can close.
