### ISSUE TITLE
Homebrew Integration

### ISSUE THREAD

**Issue by malloch** [libmapper/libmapper#52]
- [ ] create homebrew formula
- [ ] test
- [ ] submit to homwbrew
- [ ] add to release action in CI

**Comment by luzpaz** [comment]
Any traction on this ?

**Comment by luzpaz** [comment]
bumping

**Comment by malloch** [comment]
Submitted!

**Comment by luzpaz** [comment]
URL to ticket ?

**Comment by malloch** [comment]
https://github.com/Homebrew/homebrew-core/pull/140387

**Comment by malloch** [comment]
@luzpaz do you have experience with writing homebrew formulas? I'm puzzled by the Homebrew CI warning `Undeclared dependencies with linkage: liblo` (e.g. [here](https://github.com/Homebrew/homebrew-core/actions/runs/5971107443/job/16199785661?pr=140387)) since liblo is listed as a dependency in the formula.

**Comment by malloch** [comment]
I resolved the issue with the formula – now it just needs a review from anyone other than the submitter. [PR is here](https://github.com/Homebrew/homebrew-core/pull/140387) if you want to have a look and possibly review.

**Comment by malloch** [comment]
https://formulae.brew.sh/formula/libmapper
