### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by malloch** [libmapper/libmapper#54]
libmapper is currently marked as UNRELEASED at https://salsa.debian.org/multimedia-team/libmapper

- [ ] update repo
- [ ] restart conversation about releasing libmapper package(s)

**Comment by ChristianFrisson** [comment]
Hey @malloch,

I have packaged libmapper and webmapper about 3 months ago:
* https://gitlab.com/sat-metalab/forks/libmapper/-/tree/debian/main
* https://gitlab.com/sat-metalab/forks/webmapper/-/tree/debian/main

And released packages on this [SAT]Metalab PPA for ubuntu focal 20.04:
https://launchpad.net/~sat-metalab/+archive/ubuntu/metalab/

I would be happy to contribute to merge packaging upstream here, with authorship preserved.

Here are some options:
* You may pull these debian/main branches from these gitlab remotes and push them to their upstream origins here?
* I can do this if you are OK to grant me write access?

How should we proceed?

**Comment by malloch** [comment]
Thanks @ChristianFrisson! If you have time, would you be able to rebase or merge with the current main branch? There are some breaking changes wrt the python bindings which no longer use SWIG. After that I'm happy to pull your work into libmapper/main.

**Comment by bboettcher3** [comment]
Debian package for v2.3 has been uploaded to https://launchpad.net/~libmapper/+archive/ubuntu/libmapper/
Thanks @ChristianFrisson for helping with this!
