### ISSUE TITLE
python callbacks not properly registered?

### ISSUE THREAD

**Issue by DocSunset** [libmapper/libmapper#61]
In the following working example, a device is set up with two inputs and two outputs. Callbacks are registered such that when inputN is updated, outputN is set to the same value, i.e. it is expected that outputN should be a duplicate/echo/copy of whatever signal sets inputN. This is a pared-back example; in my actual use-case, the callback performs some data calibration before forwarding the calibrated data to the outgoing signal.

Instead, output1 never updates, and output2 is a duplicate/echo/copy of whatever input was received most recently by any input signal. I.e. if I connect a signal to in1, out1 doesn't update, but out2 does. It's as if the callback registered to out2 overrides the callback registered to out1?

I have no idea what is going on here, and would appreciate some help.

```python
import sys
import libmapper as mpr

def main():
  dev = mpr.Device("device")

  out1 = dev.add_signal(dir=mpr.Direction.OUTGOING
      , name="out1"
      , length=1
      , datatype=mpr.Type.FLOAT
      )

  out2 = dev.add_signal(dir=mpr.Direction.OUTGOING
      , name="out2"
      , length=1
      , datatype=mpr.Type.FLOAT
      )

  def callback(sig, val):
    print(sig)
    print(val)
    sig.set_value(val)

  in1 = dev.add_signal(dir=mpr.Direction.INCOMING
      , name="in1"
      , length=1
      , datatype=mpr.Type.FLOAT
      , callback=lambda s, e, i, v, t: callback(out1, v)
      )

  in2 = dev.add_signal(dir=mpr.Direction.INCOMING
      , name="in2"
      , length=1
      , datatype=mpr.Type.FLOAT
      , callback=lambda s, e, i, v, t: callback(out2, v)
      )

  print("{} starting main loop".format(sys.argv[0]))
  while True:
    dev.poll(1)

if __name__ == "__main__":
  try:
    main()
  except KeyboardInterrupt:
    print("Exiting {}...".format(sys.argv[0]))
```

**Comment by malloch** [comment]
Thanks @DocSunset  – you have discovered a reference counting bug in the libmapper Python bindings :)
I think the memory location for the wrapped (C-callable) function was being reused by the second lambda function, which could in turn be overwritten later and probably cause a segfault. Should be fixed now in commit #5df53f – I'll leave the issue open until you confirm.

**Comment by DocSunset** [comment]
With immense gratitude, I can confirm that the issue appears to be resolved. Many thanks!

**Comment by DocSunset** [comment]
I think I've found another incarnation of this issue, so re-opening here.

The minimum test case is very similar, but now the input signals are being created in a for loop instead of manually:

```py
import sys
import libmapper as mpr

def main():
  dev = mpr.Device("device")
  sigs = []

  def callback(val, idx):
    print(val, idx)

  for j in range(3):
    cb = lambda s, e, i, v, t: callback(v, j)
    print(cb)
    sigs.append(dev.add_signal(dir=mpr.Direction.INCOMING
      , name="in{}".format(j)
      , length=1
      , datatype=mpr.Type.FLOAT
      , callback=cb
      ))

  print("{} starting main loop".format(sys.argv[0]))
  while True:
    dev.poll(1)

if __name__ == "__main__":
  try:
    main()
  except KeyboardInterrupt:
    print("Exiting {}...".format(sys.argv[0]))
```

No matter what signal is connected to, the callback always prints as though idx=2.

I have no idea why changing to a for loop would make any difference.

**Comment by DocSunset** [comment]
Nevermind. The issue is that the lambda functions keep a reference to `j`, whose value changes. Changing the definition of the lambda fixes the problem.
`cb = lambda s, e, i, v, t, j=j: callback(v, j)`
