### ISSUE TITLE
Feature request: numpy support in python bindings

### ISSUE THREAD

**Issue by DocSunset** [libmapper/libmapper#63]
It would be splendid if numpy arrays were directly supported in the python bindings. 

For example:

- I could pass numpy arrays directly to Device::set_value and libmapper could automatically flatten them into a vector of the appropriate size (`array.flatten().to_list()` seems to work).
- I could declare a signal and pass a numpy array as its type; get_value would subsequently return numpy arrays of that type and if the signal is `Dir.INCOMING` the value element could be converted to a numpy array before being passed to the callback.
- numpy array typed signals sent from one device and received by a signal with the same type could automatically have their type preserved by the array->libmapper vector->array transformations.

**Comment by malloch** [comment]
Hi @DocSunset – in this scenario wouldn't we need the map expression engine to handle matrix arithmetic (rather than using flattened vectors) to get the results expected by the user?

**Comment by DocSunset** [comment]
I don't think it necessary to change the map expression engine. I just notice that in many of the devices I've been quickly prototyping of late that I often want to put numpy arrays into signals, and have to first convert them to lists, and also that I often immediately convert the value of a signal from a number or list into a numpy array (whether the value comes from `sig.get_value()[0]` or in an `INCOMING` signal callback). It would be convenient if the python bindings supported doing this automatically in some fashion.

**Comment by malloch** [comment]
Hi @DocSunset – Try this: [numpy branch](https://github.com/libmapper/libmapper/tree/numpy)

**Comment by bboettcher3** [comment]
@malloch this is merged afaik, can we close this?

**Comment by malloch** [comment]
This feature has been merged into main!
