### ISSUE TITLE
Segfault/core dump with certain map expressions?

### ISSUE THREAD

**Issue by DocSunset** [libmapper/libmapper#65]
I had two devices outputting vectors and one receiving a single float. I connected the two sources with the following convergent map expression:

```
y=sqrt(((x$0[0:2]-x$1)*(x$0[0:2]-x$1)).vector.sum())
```

Subsequently, the destination device and webmapper both crashed. The destination device reported the following error:

```
munmap_chunk(): invalid pointer
Aborted (core dumped)
```

Webmapper just reported `Segmentation fault (core dumped)`

I think I have encountered related crashes a few times, always related to making convergent maps.

**Comment by malloch** [comment]
This expression seems to work for me – do you have a (not) working example?

**Comment by DocSunset** [comment]
I was also unable to reproduce the crash just now. Perhaps the issue was resolved by another fix. I'll reopen it if I encounter the problem again or find a way to reproduce it reliably.
