### ISSUE TITLE
Devices linger too long after being removed

### ISSUE THREAD

**Issue by DocSunset** [libmapper/libmapper#66]
If I am working on a python script that implements a libmapper device, every time I quit the script in order to edit it, it takes several seconds before the device expires and disappears from webmapper. Before the device disappears, I cannot restart the script, or weird things happen.

To reproduce the behavior, here is a minimal device implementation:
```py
import libmapper as mpr

dev = mpr.Device("ADevice")
sig = dev.add_signal(dir=mpr.Direction.INCOMING
    , name="foo"
    , length=1
    , datatype=mpr.Type.FLOAT
    , callback=lambda s, e, i, v, t: print("callback!")
    )

while True:
  dev.poll(10)
```

Start the device `python foo.py`, and observe that it appears in Webmapper. Then halt the device script with CTRL-C and start counting down. I find it takes about 5 seconds for the device to disappear.

**Comment by DocSunset** [comment]
I naively tried adding a call to `mpr_net_poll` right before `mpr_graph_free` in `mpr_dev_free`, hoping that this would cause the freeing of the device to be broadcast to the network so that Webmapper would immediately pick up on it and remove the device, but it did not appear to work.

**Comment by malloch** [comment]
Python object `__del__()` methods are not called consistently when the program exits, so the libmapper `mpr_dev_free()` is not called automatically.  This means the devices are not sending the logout message and webmapper doesn't remove them until the local record expires.

I have added an explicit `free()` method to the python device object, but you will have to call it explicitly.

**Comment by DocSunset** [comment]
Much better! Thanks again!
