### ISSUE TITLE
python bindings installed in the wrong place on osx

### ISSUE THREAD

**Issue by mghamsar** [libmapper/libmapper#7]
the bindings are currently being installed to usr/local/lib/python2.6/site-packages

on osx they need to go under /Library/Python/2.6/site-packages

**Comment by radarsat1** [comment]
Ah, that's possible.  However, it's actually the Python setuptools that
perform the install, so it should be putting them in the right place.
 ("make install" calls out to "setup.py install")

Anyways I'll try to take a look when I get a chance.
