### ISSUE TITLE
Non-const structs disrupt windows Release build

### ISSUE THREAD

**Issue by bboettcher3** [libmapper/libmapper#73]
Hey @malloch, while I was refactoring the windows script to .ps1 instead of .bat, I changed the build config to Release (as it should be, probably), and got the following error from expression.c

```
libmapper\src\expression.c(393,1): error C2099: initializer is not a constant
libmapper\src\expression.c(395,1): error C2099: initializer is not a constant
..
..
```
The odd thing is that it skips some of the lines (see the whole error log below) and is fine with others. Do you know what might be causing this?

Full error:
`C:\Users\brady\Documents\GitHub\McGill\libmapper\src\expression.c(393,1): error C2099: initializer is not a constant [C:\Users\brady\Docum
ents\GitHub\McGill\libmapper\build\libmapper.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\src\expression.c(395,1): error C2099: initializer is not a constant [C:\Users\brady\Docum
ents\GitHub\McGill\libmapper\build\libmapper.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\src\expression.c(397,1): error C2099: initializer is not a constant [C:\Users\brady\Docum
ents\GitHub\McGill\libmapper\build\libmapper.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\src\expression.c(398,1): error C2099: initializer is not a constant [C:\Users\brady\Docum
ents\GitHub\McGill\libmapper\build\libmapper.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\src\expression.c(401,1): error C2099: initializer is not a constant [C:\Users\brady\Docum
ents\GitHub\McGill\libmapper\build\libmapper.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\src\expression.c(402,1): error C2099: initializer is not a constant [C:\Users\brady\Docum
ents\GitHub\McGill\libmapper\build\libmapper.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\src\expression.c(403,1): error C2099: initializer is not a constant [C:\Users\brady\Docum
ents\GitHub\McGill\libmapper\build\libmapper.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\src\expression.c(405,1): error C2099: initializer is not a constant [C:\Users\brady\Docum
ents\GitHub\McGill\libmapper\build\libmapper.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\src\expression.c(407,1): error C2099: initializer is not a constant [C:\Users\brady\Docum
ents\GitHub\McGill\libmapper\build\libmapper.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\src\expression.c(410,1): error C2099: initializer is not a constant [C:\Users\brady\Docum
ents\GitHub\McGill\libmapper\build\libmapper.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\src\expression.c(411,1): error C2099: initializer is not a constant [C:\Users\brady\Docum
ents\GitHub\McGill\libmapper\build\libmapper.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\src\expression.c(417,1): error C2099: initializer is not a constant [C:\Users\brady\Docum
ents\GitHub\McGill\libmapper\build\libmapper.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\src\expression.c(421,1): error C2099: initializer is not a constant [C:\Users\brady\Docum
ents\GitHub\McGill\libmapper\build\libmapper.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\src\expression.c(422,1): error C2099: initializer is not a constant [C:\Users\brady\Docum
ents\GitHub\McGill\libmapper\build\libmapper.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\src\expression.c(423,1): error C2099: initializer is not a constant [C:\Users\brady\Docum
ents\GitHub\McGill\libmapper\build\libmapper.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\src\expression.c(424,1): error C2099: initializer is not a constant [C:\Users\brady\Docum
ents\GitHub\McGill\libmapper\build\libmapper.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\src\expression.c(425,1): error C2099: initializer is not a constant [C:\Users\brady\Docum
ents\GitHub\McGill\libmapper\build\libmapper.vcxproj]`

**Comment by malloch** [comment]
Hi @bboettcher3 was this issue resolved in your PR #74?

**Comment by bboettcher3** [comment]
@malloch Nope, just building in Debug mode, if this issue gets fixed then I can change to Release.

**Comment by radarsat1** [comment]
I started poking at this to see if there was a quick fix possible but I see now that there are still some problems building liblo on Windows so I'm looking into it.

**Comment by radarsat1** [comment]
Ok, gets past the liblo build now, and I see the problem.  I assume that in Release mode, these math functions get optimized away by the compiler, maybe they are even defined as macros or something, and so it's not possible to initialize the array with the function addresses.  Only solution I can think of is to provide stubs for each one, which is kind of ugly but might work.
