### ISSUE TITLE
Undefined reference to assert in no debug mode

### ISSUE THREAD

**Issue by sofian** [libmapper/libmapper#8]
When compiling under Linux (Ubuntu 12.04) I get the following error:

```
libtool: link: gcc -std=gnu99 -Wall -I../include -I/usr/local/include -I. -g -O2 -DNDEBUG -o .libs/test test-test.o  ../src/.libs/libmapper-0.so -L/usr/local/lib /usr/local/lib/liblo.so -lpthread -lz -lm
../src/.libs/libmapper-0.so: undefined reference to `assert'
collect2: ld returned 1 exit status
make[1]: *** [test] Error 1
make[1]: Leaving directory `/media/Biquette/tats/Downloads/Web/libmapper/test'
make: *** [all-recursive] Error 1
```

The file /usr/include/assert.h exists.

I noticed that if I remove the NDEBUG flag by running "./configure --enable-debug" it compiles fine.

Full output:
http://pastebin.com/kazCPawR

**Comment by radarsat1** [comment]
Weird, I just compiled it from scratch in non-debug mode on Ubuntu 12.04 without error.  Can you pull master and try again?  It would be good when reporting bugs to mention the version hash it refers to perhaps.  (Too bad github doesn't seem to allow associating an issue report with a version!)

The issue sounds like a libc linking error of some kind, which would be highly irregular.  That said, using debug mode is actually encouraged... it provides tracing messages to help figure out what is going on.

**Comment by sofian** [comment]
I tried a fresh pull. It solved the issue. Sorry, I should have done a git pull before. However I am getting another error now but I will open a fresh issue for it.
