### ISSUE TITLE
Python module prints on import

### ISSUE THREAD

**Issue by radarsat1** [libmapper/libmapper#83]
It's a bit unusual for a Python module to [print a string on import](https://github.com/libmapper/libmapper/blob/8c9ce3c11cfafa696bddff4cb12244f3a96e34ee/bindings/python/libmapper/mapper.py.in#L17).

I suggest instead to have a function like `version_info()` that return this info in a string, and/or properties/functions that simply return the info as boolean, like `mpr.has_numpy()` or whatever.

**Comment by malloch** [comment]
Thanks for the feedback – the print was used for debugging and belonged in the test programs rather than the module. Fixed by 9d269211.
