### ISSUE TITLE
Exception when exiting from python .poll() with CTRL-C

### ISSUE THREAD

**Issue by bboettcher3** [libmapper/libmapper#85]
When exiting from a python program with CTRL-C while poll() is blocking, an exception is produced once the blocking behavior is complete:
```
 File "C:\Users\brady\anaconda3\lib\site-packages\libmapper\mapper.py", line 1133, in poll
    mpr.mpr_graph_poll(self._obj, timeout)
KeyboardInterrupt
```
We should see if we can detect the exit signal from poll and exit cleanly. This is on Windows, I'll give it a try on Ubuntu as well to see if it's the same behavior.

**Comment by malloch** [comment]
It is difficult/impossible to detect this consistently from within the libmapper package – for this reason we added an explicit `free()` method for devices which you can call from your programs. There is an example of this in [`textvector.py`](https://github.com/libmapper/libmapper/blob/main/bindings/python/testvector.py)
