### ISSUE TITLE
configuration fails with error cannot find input file: `jni/Makefile.in'

### ISSUE THREAD

**Issue by dtrejst** [libmapper/libmapper#91]
i cannot configure nor autogen the build, as it always errors out on a missing Makefile for jni.
if i try to make anyways, the process fails saying
`make[1]: *** No rule to make target 'all'.  Stop.`
What could cause this?
MacOS 10.14.6
java version "20.0.1" 2023-04-18

thank you for your help!

here is my [config.log](https://github.com/libmapper/libmapper/files/11287165/config.log)

**Comment by malloch** [comment]
Hi @dtrejst – on MacOS you will likely need to specify the jdk path, e.g. on my machine:

`./autogen.sh --with-jdk-path=/Library/Java/JavaVirtualMachines/openjdk18/Contents/Home/`

Alternatively, if you aren't going to use the Java bindings for libmapper you can skip building them:

`./autogen.sh --disable-jni`

Hope this helps!

**Comment by md-ap** [comment]
Same issue trying to build libmapper 2.3
MacOS 12.5 
Java version 20.0.1

Tried: 

./autogen.sh --with-jdk-path=/Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home/

and 

./autogen.sh --disable-jni

and still having 

config.status: error: cannot find input file: `jni/Makefile.in'

[config.log](https://github.com/libmapper/libmapper/files/11470920/config.log)

**Comment by malloch** [comment]
Hi @animico sorry to hear you are still having problems! Running `./autogen.sh --disable-jni` should have taken care of this problem. I can only think of one more thing to try: run `make clean` and then `sudo make clean` to make sure there aren't any stray configuration files in your copy, then try running `./autogen.sh --disable-jni` again. Please let me know how this goes, and please tag me (@malloch) in your reply so I get a notification!

**Comment by malloch** [comment]
Hi @animico I think I have fixed this issue – if you have time do you mind pulling the most recent commits and building again?

Thanks!

**Comment by malloch** [comment]
Closing this issue since I believe it has been fixed.
