### ISSUE TITLE
Homebrew headers are misconfigured with pkg-config

### ISSUE THREAD

**Issue by EggAllocationService** [libmapper/libmapper#95]
When installing `libmapper` from Homebrew (`brew install libmapper`), `pkg-config` will give the wrong path to the C headers.

Example:
```
$ pkg-config --cflags libmapper
-I/opt/homebrew/Cellar/libmapper/2.4.6/include/mapper -I/opt/homebrew/Cellar/liblo/0.32/include
```
The path for the libmapper headers is incorrect and should be `/opt/homebrew/Cellar/libmapper/2.4.6/include`.

The result is that the tests won't compile:
```
test.c:1:10: fatal error: 'mapper/mapper.h' file not found
#include <mapper/mapper.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
```

The `mapper` prefix is already included in the provided include path, and so it can't resolve the header correctly.

**Comment by malloch** [comment]
Should be fixed in d089314
